packages:
  - "."
  - "packages/*"
  - "apps/*"
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
  os:
    - current
    - linux
