packages:
  - "."
  - "packages/*"
  - "apps/*"

overrides:
  fast-uri: 3.1.3

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
  os:
    - current
    - linux
